# Generated by Django 4.2 on 2023-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_address_customer_country_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
