# Generated by Django 4.2 on 2023-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Slug',
            field=models.SlugField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
