# Generated by Django 4.2 on 2023-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(default='sport', max_length=64),
            preserve_default=False,
        ),
    ]
