# Generated by Django 4.2 on 2023-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Country',
            field=models.CharField(default='USA', max_length=128),
            preserve_default=False,
        ),
    ]
