# Generated by Django 4.2 on 2023-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Trending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Type',
            field=models.CharField(default='Public', max_length=64),
        ),
    ]
