# Generated by Django 4.2 on 2023-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_event_trending_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=64)),
                ('Discount', models.FloatField(default=0.0)),
            ],
        ),
    ]
