# Generated by Django 4.2 on 2023-05-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Date_of_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='Ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
