# Generated by Django 4.2 on 2023-05-30 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cart_date_of_order_remove_cart_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ordered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
