# Generated by Django 4.2 on 2023-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
